### ISSUE TITLE
Request to made the button toggle-able

### ISSUE THREAD

**Issue by samuelwyc** [Bryanx/themed-toggle-button-group#1]
in multiple selection, after toggle once, it will be "true" always, if I click back on the same button, it should be change to "false" instead staying "true" forever

**Comment by samuelwyc** [comment]
![image](https://user-images.githubusercontent.com/7992632/76487450-7a036380-645d-11ea-9d5f-8e1fee268f0a.png)
Have made some changes here to support that

**Comment by Bryanx** [comment]
Hey, thanks for the suggestion! Good point, I hadn't thought of that. I will implement it in the next minor release. Also, sometimes it is necessary to prevent deselecting buttons. I will also add a required amount attribute, so people can select how many buttons are required.
