### ISSUE TITLE
Handle : selectButtonWithAnimation throws IllegalStateException Cannot start this animator on a detached view!

### ISSUE THREAD

**Issue by JobGetabu** [Bryanx/themed-toggle-button-group#13]
java.lang.IllegalStateException: Cannot start this animator on a detached view!

**Comment by Bryanx** [comment]
I am going to need some more information to help with this.

**Comment by Bryanx** [comment]
Closing this for now. Please open a new ticket if you have a similar issue.

**Comment by MrCode403** [comment]
Error
![Screenshot_20220701-133419_CodeAssist](https://user-images.githubusercontent.com/100035516/176852350-684545b9-a8c0-461b-b7cc-bde630259c5c.jpg)

My Code
![Screenshot_20220701-133520_CodeAssist](https://user-images.githubusercontent.com/100035516/176852486-135d0a68-7355-4b86-8a12-3a77414ede97.jpg)
