### ISSUE TITLE
Refactor with recyclerview

### ISSUE THREAD

**Issue by PlexPt** [Bryanx/themed-toggle-button-group#14]
That's more flexible

**Comment by PlexPt** [comment]
see
https://stackoverflow.com/questions/49973244/android-gridlayout-with-dynamic-number-of-columns-per-row/49973416#49973416

**Comment by Bryanx** [comment]
I'm not sure if this is relevant anymore, note that this comment is from 2018. You can easily dynamically add and spread out items using justifyContent="space_between".
