### ISSUE TITLE
Last line disappears when text size of specific item is long

### ISSUE THREAD

**Issue by WebDev301** [Bryanx/themed-toggle-button-group#15]
Hi. I am going to create a woman health project using your library but I encountered an issue.
When I try to create multiple lines of different sizes of items, the last line disappears.
My code looks like this:

```
<style name="SymptomsItemStyle">
        <item name="android:layout_width">0dp</item>
        <item name="android:layout_height">wrap_content</item>
        <item name="android:layout_marginTop">5dp</item>
        <item name="android:layout_marginBottom">5dp</item>
        <item name="toggle_paddingTop">10dp</item>
        <item name="toggle_paddingBottom">10dp</item>
        <item name="layout_flexGrow">1</item>
    </style>

<nl.bryanderidder.themedtogglebuttongroup.ThemedToggleButtonGroup
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            app:toggle_selectableAmount="9"
            app:toggle_requiredAmount="0"
            app:toggle_horizontalSpacing="0dp"
            app:flexWrap="wrap"
            >

            <nl.bryanderidder.themedtogglebuttongroup.ThemedButton
                style="@style/SymptomsItemStyle"
                app:toggle_text="@string/intensity_light" />

            <nl.bryanderidder.themedtogglebuttongroup.ThemedButton
                style="@style/SymptomsItemStyle"
                android:layout_marginStart="10dp"
                android:layout_marginEnd="10dp"
                app:toggle_text="asdfasdfa" />

            <nl.bryanderidder.themedtogglebuttongroup.ThemedButton
                style="@style/SymptomsItemStyle"
                app:toggle_text="@string/intensity_severe" />

            <nl.bryanderidder.themedtogglebuttongroup.ThemedButton
                style="@style/SymptomsItemStyle"
                app:layout_wrapBefore="true"
                app:toggle_text="@string/intensity_light" />

            <nl.bryanderidder.themedtogglebuttongroup.ThemedButton
                style="@style/SymptomsItemStyle"
                android:layout_marginStart="10dp"
                android:layout_marginEnd="10dp"
                app:toggle_text="@string/intensity_average" />

            <nl.bryanderidder.themedtogglebuttongroup.ThemedButton
                style="@style/SymptomsItemStyle"
                app:toggle_text="@string/intensity_severe" />

            <nl.bryanderidder.themedtogglebuttongroup.ThemedButton
                style="@style/SymptomsItemStyle"
                app:layout_wrapBefore="true"
                app:toggle_text="@string/intensity_light" />

            <nl.bryanderidder.themedtogglebuttongroup.ThemedButton
                style="@style/SymptomsItemStyle"
                android:layout_marginStart="10dp"
                android:layout_marginEnd="10dp"
                app:toggle_text="@string/intensity_average" />

            <nl.bryanderidder.themedtogglebuttongroup.ThemedButton
                style="@style/SymptomsItemStyle"
                app:toggle_text="@string/intensity_severe" />

        </nl.bryanderidder.themedtogglebuttongroup.ThemedToggleButtonGroup>
```
![issue](https://user-images.githubusercontent.com/51168024/99281639-b9484680-286d-11eb-8f0a-055d59b16b5b.png)

How can I fix this issue?
Hope to hearing from you soon.
Thanks.

**Comment by Bryanx** [comment]
Hey thanks for reporting. This is an issue with flexboxlayout, I think you might be able to fix this by giving your buttons `        app:layout_minHeight="40dp"`.

**Comment by WebDev301** [comment]
Thanks for your responding. 
In my opinion, that is not an issue with height of each item.
This is my full code of layout and screenshot.

`
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical"
    tools:context=".cycle.SymptomsActivity">

    <include android:id="@+id/toolbar_area"
        layout="@layout/toolbar"/>

    <LinearLayout
        android:id="@+id/flow_area"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_marginStart="@dimen/layout_margin_h"
        android:layout_marginEnd="@dimen/layout_margin_h"
        android:orientation="vertical">

        <TextView
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_marginTop="30dp"
            android:layout_marginBottom="10dp"
            android:textSize="20sp"
            android:text="@string/flow"
            android:textColor="@color/black"/>

        <nl.bryanderidder.themedtogglebuttongroup.ThemedToggleButtonGroup
            android:id="@+id/flow_group"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            app:toggle_selectableAmount="1"
            >

            <nl.bryanderidder.themedtogglebuttongroup.ThemedButton
                style="@style/SymptomsItemStyle"
                app:toggle_text="@string/intensity_light" />

            <nl.bryanderidder.themedtogglebuttongroup.ThemedButton
                style="@style/SymptomsItemStyle"
                app:toggle_text="@string/intensity_average" />

            <nl.bryanderidder.themedtogglebuttongroup.ThemedButton
                style="@style/SymptomsItemStyle"
                app:toggle_text="@string/intensity_heavy" />


        </nl.bryanderidder.themedtogglebuttongroup.ThemedToggleButtonGroup>

    </LinearLayout>

    <LinearLayout
        android:id="@+id/pain_area"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_marginStart="@dimen/layout_margin_h"
        android:layout_marginEnd="@dimen/layout_margin_h"
        android:orientation="vertical">

        <TextView
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_marginTop="30dp"
            android:layout_marginBottom="10dp"
            android:textSize="20sp"
            android:text="@string/pain"
            android:textColor="@color/black"/>

        <nl.bryanderidder.themedtogglebuttongroup.ThemedToggleButtonGroup
            android:id="@+id/pain_group"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            app:toggle_selectableAmount="1" >

            <nl.bryanderidder.themedtogglebuttongroup.ThemedButton
                style="@style/SymptomsItemStyle"
                app:toggle_text="@string/intensity_light" />

            <nl.bryanderidder.themedtogglebuttongroup.ThemedButton
                style="@style/SymptomsItemStyle"
                app:toggle_text="@string/intensity_average" />

            <nl.bryanderidder.themedtogglebuttongroup.ThemedButton
                style="@style/SymptomsItemStyle"
                app:toggle_text="@string/intensity_severe" />


        </nl.bryanderidder.themedtogglebuttongroup.ThemedToggleButtonGroup>

    </LinearLayout>

    <LinearLayout
        android:id="@+id/condition_area"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_marginStart="@dimen/layout_margin_h"
        android:layout_marginEnd="@dimen/layout_margin_h"
        android:orientation="vertical">

        <TextView
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_marginTop="30dp"
            android:layout_marginBottom="10dp"
            android:textSize="20sp"
            android:text="@string/physical_conditions"
            android:textColor="@color/black"/>

        <nl.bryanderidder.themedtogglebuttongroup.ThemedToggleButtonGroup
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            app:toggle_selectableAmount="9"
            app:toggle_requiredAmount="0"
            app:toggle_horizontalSpacing="0dp"
            app:flexWrap="wrap"
            >
            <nl.bryanderidder.themedtogglebuttongroup.ThemedButton
                style="@style/SymptomsItemStyle"
                app:toggle_text="@string/intensity_light" />
            <nl.bryanderidder.themedtogglebuttongroup.ThemedButton
                style="@style/SymptomsItemStyle"
                android:layout_marginStart="10dp"
                android:layout_marginEnd="10dp"
                app:toggle_text="asdfasdfa" />
            <nl.bryanderidder.themedtogglebuttongroup.ThemedButton
                style="@style/SymptomsItemStyle"
                app:toggle_text="@string/intensity_severe" />
            <nl.bryanderidder.themedtogglebuttongroup.ThemedButton
                style="@style/SymptomsItemStyle"
                app:layout_wrapBefore="true"
                app:toggle_text="@string/intensity_light" />
            <nl.bryanderidder.themedtogglebuttongroup.ThemedButton
                style="@style/SymptomsItemStyle"
                android:layout_marginStart="10dp"
                android:layout_marginEnd="10dp"
                app:toggle_text="@string/intensity_average" />
            <nl.bryanderidder.themedtogglebuttongroup.ThemedButton
                style="@style/SymptomsItemStyle"
                app:toggle_text="@string/intensity_severe" />
            <nl.bryanderidder.themedtogglebuttongroup.ThemedButton
                style="@style/SymptomsItemStyle"
                app:layout_wrapBefore="true"
                app:toggle_text="@string/intensity_light" />
            <nl.bryanderidder.themedtogglebuttongroup.ThemedButton
                style="@style/SymptomsItemStyle"
                android:layout_marginStart="10dp"
                android:layout_marginEnd="10dp"
                app:toggle_text="@string/intensity_average" />
            <nl.bryanderidder.themedtogglebuttongroup.ThemedButton
                style="@style/SymptomsItemStyle"
                app:toggle_text="@string/intensity_severe" />
        </nl.bryanderidder.themedtogglebuttongroup.ThemedToggleButtonGroup>

    </LinearLayout>

</LinearLayout>
`

![full](https://user-images.githubusercontent.com/51168024/99479886-04f41080-2992-11eb-98c2-5831a1d5791e.png)

As you can see in this layout, this shows three sections(flow, pain, physical conditions)
If I remove 'flow' or 'pain' section, the last line of 'physical conditions' does not disappear.

Do you think that issue is also related to flexboxlayout?
I want to know your thought asap. Thanks

**Comment by Bryanx** [comment]
Yes, Flexboxlayout has difficulty getting the total height when the container is set to `height="wrap_content"` + `app:flexWrap="wrap"` and the height of each individual item set to `wrap_content`. It then has to calculate the total height based on the text size which fails for some reason. I have tested your situation and setting the minHeight fixed the issue.

**Comment by Bryanx** [comment]
Assuming this solved the issue. Closing this for now.
