### ISSUE TITLE
Set selected button colour not working

### ISSUE THREAD

**Issue by jadenwjh** [Bryanx/themed-toggle-button-group#19]
setSelectedBgColor() shows incorrect color. For some reason the colors always seem to be different shades of purple, whereby my intended color is blended with the default color (denim). Here is my code:

<img width="1439" alt="Screenshot 2021-01-02 at 6 17 29 PM" src="https://user-images.githubusercontent.com/62279469/103455280-c8545c80-4d26-11eb-812a-7e02b2f75702.png">

**Comment by Bryanx** [comment]
Hello, selectedBgColor expects a color. When you pass R.color.blue you are passing a reference to a color. In order to pass the color you can do something like this:
```kotlin
int color = ContextCompat.getColor(this, android.R.color.holo_green_dark);
themedButton.setSelectedBgColor(color);
```

**Comment by jadenwjh** [comment]
@Bryanx thanks, it's working now
