### ISSUE TITLE
I can't select button programmatically

### ISSUE THREAD

**Issue by ra1popov** [Bryanx/themed-toggle-button-group#20]
Hello,

How select ThemedToggleButton programmatically? I try use the method setSelected, but it doesn't work.

**Comment by Bryanx** [comment]
Hi, it's in the readme:
```kotlin
buttonGroup.selectButtonWithAnimation(btn)
buttonGroup.selectButton(btn)
````

**Comment by ra1popov** [comment]
Thanks, how invoke deselect? The method buttonGroup.selectButton(btn) don't work and i can't find buttonGroup.DEselectButton(btn)

**Comment by Bryanx** [comment]
I think there is a bug with selectButton(), it does not deselect a button after firing it when a button is selected. I will look into this. Selecting a button with selectButton() does work for me.

For now you can use selectButtonWithAnimation to also deselect a button.

**Comment by ra1popov** [comment]
The method selectButtonWithAnimation is works. Thank you so much!
