### ISSUE TITLE
how to select or deselect button programatically

### ISSUE THREAD

**Issue by codepro450** [Bryanx/themed-toggle-button-group#22]
There is no method to select or deselect these Themed buttons, if I  use setSelected(true/false), they stop working....

**Comment by Bryanx** [comment]
There is a select method on the button group, you can pass in the ThemedButton or its resid. If the button is already selected it deselects the button:
```kotlin
buttonGroup.selectButtonWithAnimation(btn)
buttonGroup.selectButton(btn)
```
