### ISSUE TITLE
wanted  then  to be in a single line  

### ISSUE THREAD

**Issue by priyanshumaurya8868** [Bryanx/themed-toggle-button-group#26]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
[
![image](https://user-images.githubusercontent.com/68337520/126592939-baa151b8-032a-437a-a8d5-7d9fd9802760.png)
](url)

**Comment by Bryanx** [comment]
Hi, I'm not sure what you are asking. You don't want the text inside the buttons to wrap?
