### ISSUE TITLE
How can I disable it?

### ISSUE THREAD

**Issue by satoshinosekai** [Bryanx/themed-toggle-button-group#30]
mBinding.reviewResultToggle.isClickable = false
mBinding.reviewResultToggle.isActivated = false
mBinding.reviewResultToggle.isEnabled = false
mBinding.reviewResultToggle.isSelected = false
for (button in mBinding.reviewResultToggle.buttons) {
    button.isClickable = false
    button.isActivated = false
    button.isEnabled = false
    button.isSelected = false
}
Also not work.
Can I lock the change?

**Comment by Bryanx** [comment]
Hi, thanks for taking an interest in this project. I am closing this as this is a duplicate of #12 . Any further discussion can move to that ticket.
