### ISSUE TITLE
Handle : selectButtonWithAnimation throws IllegalStateException Cannot start this animator on a detached view!

### ISSUE THREAD

**Issue by ISEKHON** [Bryanx/themed-toggle-button-group#34]
The error i got 
![Screenshot_20220701-133419_CodeAssist](https://user-images.githubusercontent.com/100035516/176852823-c2365024-7dc3-48ad-8c24-e7b47e50a197.jpg)

And my code is
![Screenshot_20220701-133520_CodeAssist](https://user-images.githubusercontent.com/100035516/176852852-98786cbc-5297-4848-ad70-b7d1df706742.jpg)

Please help me to resolve this

**Comment by ISEKHON** [comment]
I also tried `group.selectButtonWithAnimation(R.id.btn1);` and `group.selectButtonWithAnimation(themeButton);`

**Comment by Bryanx** [comment]
You are trying to click the button before it is attached. If you just want to set the initial selection you can use  `ThemedButton.isChecked = true`.

**Comment by ISEKHON** [comment]
Ok thanks for replying but i have tried 
`ThemedButton bynn = findViewById(R.id.btn2);	
group.selectButton(bynn.getId());` 
this code and its working 

But throwing same error when i try to select with animation `group.selectButtonWithAnimation(bynn.getId());`
