### ISSUE TITLE
select/toggle buttons programmatically

### ISSUE THREAD

**Issue by okanulkr** [Bryanx/themed-toggle-button-group#5]
Is there a way to select/toggle the buttons programmatically?

**Comment by Bryanx** [comment]
You can call [selectButton()](https://github.com/Bryanx/themed-toggle-button-group/blob/2cd3ffb49b5c0e0acd862f3557ab660d71ad236d/library/src/main/java/nl/bryanderidder/themedtogglebuttongroup/ThemedToggleButtonGroup.kt#L177) or [selectButtonWithAnimation()](https://github.com/Bryanx/themed-toggle-button-group/blob/2cd3ffb49b5c0e0acd862f3557ab660d71ad236d/library/src/main/java/nl/bryanderidder/themedtogglebuttongroup/ThemedToggleButtonGroup.kt#L148) on ThemedButtonToggleGroup. On these methods you can pass the the resource id of the button or the button itself. I will add it to the readme to make this more clear.

**Comment by okanulkr** [comment]
Thank you for your answer man, also for the library.
