### ISSUE TITLE
add the items programmatically

### ISSUE THREAD

**Issue by Baraka1Ahmad** [Bryanx/themed-toggle-button-group#8]
Does it support programmatically inserting items into an array for example?

**Comment by Bryanx** [comment]
I'm assuming you want to keep an array with selected buttons? You can access the property in the group: 
themedToggleButtonGroup.selectedButtons.

If you want to do something else you can listen on selection changes:
themedToggleButtonGroup.setOnSelectListener()

**Comment by Baraka1Ahmad** [comment]
Hi Mr. @Bryanx
Thank you very much for this great effort...

 
My question was about I received an array from the server.
This array in each product contains a different number of values.
Therefore I need to enter these values programmatically, I solved the problem in this way as shown.
![image](https://user-images.githubusercontent.com/36124035/86517323-bf92d480-be30-11ea-9d71-b945112e847b.png)

Now I have a problem with how to make the buttons remain their original width and enter a new line


![WhatsApp Image 2020-07-04 at 8 02 03 PM](https://user-images.githubusercontent.com/36124035/86517424-77c07d00-be31-11ea-80bf-8ce7181ea91d.jpeg)

**Comment by Bryanx** [comment]
Right, so you want the buttons to move the next line when too many are added. Add ```app:flexWrap="wrap"``` to the buttonGroup in the layout file. Or programmatically: ```buttonGroup.setFlexWrap(FlexWrap.WRAP)```

**Comment by Baraka1Ahmad** [comment]
You are really amazing @Bryanx 
Thanks a lot for the help ❤ .
