### ISSUE TITLE
Add Font family

### ISSUE THREAD

**Issue by Baraka1Ahmad** [Bryanx/themed-toggle-button-group#9]
Hello, It's a very amazing library
But I don’t know how to find the font path to add here "` btn.setFontFamily()` "
here in my font file
![image](https://user-images.githubusercontent.com/36124035/86780128-0ec14b00-c065-11ea-9525-336db2646761.png)
how can I find his path
Thanks in advance for help.

**Comment by Bryanx** [comment]
setFontFamily() actually creates a new font asset. To use existing assets you can do this:
```kotlin
btn.applyToTexts {
  it.setTypeface(ResourcesCompat.getFont(context, R.font.stc), Typeface.BOLD)
}
```

**Comment by Baraka1Ahmad** [comment]
I write java code, I faced a problem with this `btn.applyToTexts()`
it takes some parameters 
can you please write java code for me please . 
![image](https://user-images.githubusercontent.com/36124035/86898032-da0acd80-c110-11ea-9435-f01f1ac061f7.png)

**Comment by Bryanx** [comment]
Ah I didn't notice. Here it is in Java:
```
btn.applyToTexts(txt -> {
  txt.setTypeface(ResourcesCompat.getFont(context, R.font.stc), Typeface.BOLD);
});
```

**Comment by Baraka1Ahmad** [comment]
Hi @Bryanx 
I'm sorry For Disturb
But the problem remains
![image](https://user-images.githubusercontent.com/36124035/87156764-d9fffe80-c2c5-11ea-9ebd-9f60c86be101.png)
txt doesn't have setTypeface method
can you please healp ?

**Comment by Bryanx** [comment]
Alternatively you could set the fonts individually. I didn't know kotlin function parameter were not compatible with java.
```
btn.getTvText().setTypeface(...);
btn.getTvSelectedText().setTypeface(...);
```

**Comment by Baraka1Ahmad** [comment]
Thanks, it is working fine now
But there are still some Java related issues like getting `ThemedToggleButtonGroup` to take `wrap_content` programmatically and so on.
Also, the command related to the action of `buttonGroup.setOnSelectListener`

But I think it works great with Kotlin
It's a great effort from you, thank you very much for your help.

**Comment by dev-abhisek30** [comment]
> setFontFamily() actually creates a new font asset. To use an existing font resource you can do this:
> 
> ```kotlin
> btn.applyToTexts {
>   it.setTypeface(ResourcesCompat.getFont(context, R.font.stc), Typeface.BOLD)
> }
> ```
> 
> I agree this may a bit clumsy/confusing. I will consider to update the api in the next minor version.

@Bryanx Do we have a update on this enhancement  ?
